# These are supported funding model platforms

github: # [Bardioc26]
ko_fi: # Bardioc26 [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/M4M11S4NJR)
custom: # ['ko-fi.com/bamort']
